# Generated by Django 5.1.5 on 2025-05-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_acquired', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('staff', 'Salaries and Wages'), ('utilities', 'Utilities'), ('repairs', 'Repairs and Maintenance'), ('supplies', 'Cleaning & Room Supplies'), ('fnb', 'Food and Beverage'), ('admin', 'Administrative'), ('marketing', 'Sales and Marketing'), ('finance', 'Finance Costs'), ('depreciation', 'Depreciation'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('drawn_by', models.CharField(default='staff', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rooms', 'Rooms'), ('fnb', 'Food & Beverage'), ('party', 'Party'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_from', models.CharField(default='staff', max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
