# Generated by Django 5.1.5 on 2025-05-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_of_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('retaurant', 'Retaurant'), ('accomodation', 'Accomodation'), ('party', 'Party'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drawn', models.CharField(default='staff', max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='revenue',
            name='category',
            field=models.CharField(choices=[('rooms', 'Rooms'), ('Food & Beverage', 'Food & Beverage'), ('party', 'Party'), ('other', 'Other')], max_length=20),
        ),
    ]
