# Generated by Django 5.2 on 2025-05-16 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liability',
            options={'ordering': ['-due_date', '-id'], 'verbose_name': 'Liability', 'verbose_name_plural': 'Liabilities'},
        ),
        migrations.RemoveField(
            model_name='liability',
            name='name',
        ),
        migrations.AddField(
            model_name='liability',
            name='attachment',
            field=models.FileField(blank=True, help_text='Supporting document (optional).', null=True, upload_to='attachments/liability/'),
        ),
        migrations.AddField(
            model_name='liability',
            name='category',
            field=models.CharField(choices=[('LOAN', 'Loan / Debt'), ('PAYABLE', 'Accounts Payable'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Liability Category'),
        ),
        migrations.AddField(
            model_name='liability',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liabilities_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liability',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Liability Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liability',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='liability',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liabilities_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liability',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='liability',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
