# Generated by Django 5.1.5 on 2025-06-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_budget_created_by_budget_expense_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
