# Generated by Django 5.1.5 on 2025-06-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_budget_end_date_budget_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
