# Generated by Django 5.1.5 on 2025-07-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_budgetline_actual_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('staff', 'Salaries and Wages'), ('utilities', 'Utilities'), ('repairs', 'Repairs and Maintenance'), ('supplies', 'Cleaning & Room Supplies'), ('fnb', 'Food and Beverage'), ('admin', 'Administrative'), ('marketing', 'Sales and Marketing'), ('finance', 'Finance Costs'), ('depreciation', 'Depreciation'), ('other', 'Other'), ('other_pack', 'Other_Packages')], max_length=100, null=True),
        ),
    ]
