# Generated by Django 5.1.5 on 2025-08-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_liability_date_received_liability_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liability',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='liability',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
    ]
