# Generated by Django 5.1.5 on 2025-08-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_liability_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liability',
            name='amount_paid',
        ),
        migrations.AlterField(
            model_name='liability',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
