# Generated by Django 5.2.7 on 2025-11-16 18:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room_bookings', '0011_roomreservation_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_bookings.room')),
            ],
            options={
                'ordering': ['-audit_date'],
                'unique_together': {('room', 'audit_date')},
            },
        ),
        migrations.CreateModel(
            name='RoomAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('installation_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('working', 'Working'), ('maintenance', 'Needs Maintenance'), ('broken', 'Broken'), ('replaced', 'Replaced')], default='working', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assets', to='room_bookings.room')),
            ],
            options={
                'unique_together': {('room', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('working', 'Working'), ('maintenance', 'Needs Maintenance'), ('broken', 'Broken'), ('replaced', 'Replaced')], max_length=20)),
                ('condition_notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='asset_audits/%Y/%m/')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_items', to='assets.monthlyaudit')),
                ('room_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.roomasset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Check'), ('repair', 'Repair'), ('replacement', 'Replacement'), ('cleaning', 'Cleaning')], max_length=50)),
                ('description', models.TextField()),
                ('technician', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('room_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='assets.roomasset')),
            ],
        ),
    ]
