# Generated by Django 5.1.5 on 2025-06-04 06:52

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='category_items')),
                ('grouping', models.CharField(choices=[('Appetizers', 'Appetizers'), ('Starter', 'Starter'), ('Main Dishes', 'Main Dishes'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks'), ('Breakfast', 'Breakfast')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='menu_items')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='inventory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailySpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('dining_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='inventory.diningarea')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_id', models.CharField(default=inventory.models.generate_random_id, editable=False, max_length=6, unique=True)),
                ('customer_name', models.CharField(blank=True, default='Customer', max_length=255, null=True)),
                ('served_by', models.CharField(blank=True, default='Waitress', max_length=255, null=True)),
                ('special_notes', models.TextField(default='Null')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('payment_mode', models.CharField(choices=[('NO PAYMENT', 'NO PAYMENT'), ('CASH', 'CASH'), ('MOMO PAY', 'MOMO PAY'), ('AIRTEL PAY', 'AIRTEL PAY'), ('INVOICE', 'INVOICE')], default='NO PAYMENT', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID / Invoice Number', max_length=100, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dining_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.diningarea')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.table')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, default='Customer', max_length=255, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Cooked', 'Completed'), ('Served', 'Served'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('special_notes', models.CharField(blank=True, choices=[('nothing', 'Nothing'), ('strongly spiced', 'Strongly Spiced'), ('midly spiced', 'Mildly Spiced'), ('chips', 'Chips'), ('rice', 'Rice'), ('posho', 'Posho'), ('rice_posho', 'Rice + Posho'), ('chips_rice', 'Chips + Rice'), ('chips_posho', 'Chips + Posho')], default='nothing', max_length=50, null=True)),
                ('order_type', models.CharField(choices=[('Dine-In', 'Dine-In'), ('Take-Away', 'Take-Away')], default='Dine-In', max_length=10)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('dining_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.diningarea')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory.ordertransaction')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.table')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['-order_date'],
            },
        ),
    ]
