# Generated by Django 5.1.5 on 2025-06-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
