# Generated by Django 5.1.5 on 2025-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_bookings', '0005_customer_customerid_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='nin_pictures/'),
        ),
    ]
